# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-18 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRegistration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regdetails',
            name='name',
            field=models.TextField(max_length=200),
        ),
    ]
